/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesGraficas;

import main.PedraPapelTesoura;
import main.CPU;
import main.Jogador;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.ImageIcon;

/**
 *
 * @author berna
 */

public class Batalha extends javax.swing.JFrame {

    /**
     * instancia uma CPU.
     */
    CPU c;
    
    /**
     * instancia um valor de resultado.
     */
    int res;
    
    /**
     * Método Construtor que centraliza a janela da batalha, cria a CPU, deixa o botão "Resultado" invisível para que só esteja disponível após o resultado.
     * Seta os sprites da CPU e do Jogador e trate a exceção caso o parâmetro passado leve a um endereço inexistente.
     */
    public Batalha() {
        initComponents();
        setLocationRelativeTo(null);
        c = CPUPOKE();      
        BotaoResultado.setVisible(false);
        SpriteCPU.setIcon(c.getPokemon().getImagem());
        Jogador j = leJogador();
        try {
            SpriteJogador.setIcon(j.getPokemon().getImagem());
        } catch (Exception e){
            System.out.println(e.toString());
        }        
    }
    
    /**
     * O método instancia um jogador como NULL, lê o jogador salvo na janela de Seleção e retorna o jogador.
     * @return
     */
    public Jogador leJogador() {
        Jogador j = null;
        try { 
            FileInputStream fis = new FileInputStream("Jogador.ser");            
            ObjectInputStream ois = new ObjectInputStream(fis);
            j = (Jogador) ois.readObject();
        } catch (Exception i) {
            System.out.println(i.toString());
        }
        return j;
    }
    
    /**
     * O método instancia um jogador como NULL,lê o jogador salvo na janela de Seleção e retorna o jogador.
     */
    private CPU CPUPOKE() {
        // TODO add your handling code here:
        CPU c = new CPU();
        c.setPokemon(c.geraPokemon());        
        return c;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoPedra = new Botao(1, "src/PedraPapelTesoura/bp.png");
        BotaoPapel = new Botao(2, "src/PedraPapelTesoura/bpa.png");
        BotaoTesoura = new Botao(3, "src/PedraPapelTesoura/bt.png");
        SpriteJogador = new javax.swing.JLabel();
        BalaoJogador = new javax.swing.JLabel();
        SpriteCPU = new javax.swing.JLabel();
        BalaoCPU = new javax.swing.JLabel();
        BotaoResultado = new javax.swing.JButton();
        Fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 480));
        setMinimumSize(new java.awt.Dimension(800, 480));
        setPreferredSize(new java.awt.Dimension(800, 480));
        setResizable(false);
        getContentPane().setLayout(null);

        BotaoPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PedraPapelTesoura/Pedra.png"))); // NOI18N
        BotaoPedra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PedraPapelTesoura/Pedra.png"))); // NOI18N
        BotaoPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPedraActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoPedra);
        BotaoPedra.setBounds(80, 340, 130, 90);

        BotaoPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PedraPapelTesoura/Papel.png"))); // NOI18N
        BotaoPapel.setText("jButton4");
        BotaoPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPapelActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoPapel);
        BotaoPapel.setBounds(340, 340, 130, 90);

        BotaoTesoura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PedraPapelTesoura/Tesoura.png"))); // NOI18N
        BotaoTesoura.setText("jButton5");
        BotaoTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTesouraActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoTesoura);
        BotaoTesoura.setBounds(580, 340, 120, 90);
        getContentPane().add(SpriteJogador);
        SpriteJogador.setBounds(180, 200, 150, 100);
        getContentPane().add(BalaoJogador);
        BalaoJogador.setBounds(190, 160, 60, 90);
        getContentPane().add(SpriteCPU);
        SpriteCPU.setBounds(490, 200, 130, 120);
        getContentPane().add(BalaoCPU);
        BalaoCPU.setBounds(490, 200, 60, 60);

        BotaoResultado.setText("Resultado");
        BotaoResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoResultado);
        BotaoResultado.setBounds(330, 300, 140, 23);

        Fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagensDeFundo/pokemon_x_and_y_battle_background_16_by_phoenixoflight92-d8594wx.png"))); // NOI18N
        getContentPane().add(Fundo);
        Fundo.setBounds(0, 0, 800, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Esse método chama a jogada do jogador e da CPU, faz um novo jogo de pedra papael tesoura, passa para esse jogo criado a jogada do jogador e da CPU
     * faz com que o atributo 'res' receba o resultado, faz o balão de jogada do jogador e da CPU aparecerem na tela,
     * some com os botões de escolha para que nenhuma nova jogada seja feita,
     * salva o valor do resultado,
     * torna visível o votão do resultado.
     */
    private void fazerJogada(int jogada, String url){
        j=leJogador();
        j.setJogada(jogada);
        c.cpuJogada();
        PedraPapelTesoura p = new PedraPapelTesoura(j, c);
        res = p.jogaPedraPapelTesoura();
        ImageIcon ij = new ImageIcon(url);
        BalaoJogador.setIcon(ij);
        BalaoJogador.setVisible(true);
        BalaoCPU.setIcon(c.getIcone());
        BalaoCPU.setVisible(true);        
        BotaoPedra.setVisible(false);
        BotaoPapel.setVisible(false);
        BotaoTesoura.setVisible(false);
        salvaR(res);
        BotaoResultado.setVisible(true);
    }
    
    /**
     * Ao clicar no botão da pedra, realiza-se a chamada do método fazer jogada, 
     * passando a pedra como parâmetro.
     */
    private void BotaoPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPedraActionPerformed
        fazerJogada(((Botao)BotaoPedra).getJogada(),((Botao)BotaoPedra).getUrlIcone());
    }//GEN-LAST:event_BotaoPedraActionPerformed

    /**
     * Ao clicar no botão do papel, realiza-se a chamada do método fazer jogada, 
     * passando o papel como parâmetro.
     */
    private void BotaoPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPapelActionPerformed
        // TODO add your handling code here:
        fazerJogada(((Botao)BotaoPapel).getJogada(),((Botao)BotaoPapel).getUrlIcone());
    }//GEN-LAST:event_BotaoPapelActionPerformed

    /**
     * Ao clicar no botão da tesoura, realiza-se a chamada do método fazer jogada, 
     * passando a tesoura como parâmetro.
     */
    private void BotaoTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTesouraActionPerformed
        // TODO add your handling code here:
    fazerJogada(((Botao)BotaoTesoura).getJogada(), ((Botao)BotaoTesoura).getUrlIcone());;
    }//GEN-LAST:event_BotaoTesouraActionPerformed

    /**
     * Ao clicar no botão resultado, é criado uma janela de resultado. Essa janela fica visível e fecha a janela de batalha.
     */
    private void BotaoResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoResultadoActionPerformed
        // TODO add your handling code here:
        Resultado resultado;
        resultado = new Resultado();
        resultado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoResultadoActionPerformed

    /**
     * Esse método salva o valor 'i', que representa o resultado do jogo. 
     */
    public void salvaR(int i) {
        try{
        FileOutputStream fos = new FileOutputStream("resultado.ser");
        ObjectOutputStream oos = new ObjectOutputStream(fos);
        oos.writeObject(i);
        oos.flush();        
        
        } catch(Exception ex){
            System.out.println(ex.toString());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    
    //public 
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }        
        
       
               
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Batalha().setVisible(true);
            }
        });
    }
    private Jogador j;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalaoCPU;
    private javax.swing.JLabel BalaoJogador;
    private javax.swing.JButton BotaoPapel;
    private javax.swing.JButton BotaoPedra;
    private javax.swing.JButton BotaoResultado;
    private javax.swing.JButton BotaoTesoura;
    private javax.swing.JLabel Fundo;
    private javax.swing.JLabel SpriteCPU;
    private javax.swing.JLabel SpriteJogador;
    // End of variables declaration//GEN-END:variables
}
